administracja/urls.py
from django.urls import path, include,reverse
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView
from . import views
app_name='administracja'
urlpatterns=[
    #path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(success_url = reverse_lazy('administracja:password_change_done')), name='password_change_done'),

    
    path('login/',auth_views.LoginView.as_view(),name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('',views.dashboard,name="dashboard"),
    path('',views.index,name="index"),
    path('',views.lista_lekarzy,name="lista_lekarzy"),
    path('lista_lekarzy',views.lista_lekarzy,name="lista_lekarzy"),
    path('register/',views.register,name="register"),
    path('password_change/', auth_views.PasswordChangeView.as_view(success_url='done'), name='password_change'),
    
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
        path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
        name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,
        name='product_detail'),
   
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

przychodnia/urls.py
from django.contrib import admin
from django.urls import path,include
from administracja import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("administracja.urls")),
    path('administracja', include('administracja.urls'),),
    path('', include('administracja.urls', namespace='administracja')),
]

administracja/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

User = get_user_model()

# Create your models here.
class Lekarze(models.Model):
    numer_lek = models.IntegerField(primary_key=True)
    imie = models.TextField(blank=True, null=True)
    nazwisko = models.TextField(blank=True, null=True)
    specjalizacja = models.TextField(blank=True, null=True)
    

    class Meta:
        managed = False
        db_table = 'lekarze'

class Pacjenci(models.Model):
    numer_pac = models.IntegerField(primary_key=True)
    imie = models.TextField(blank=True, null=True)
    nazwisko = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'pacjenci'


class Wizyta(models.Model):
    numer_pacjenta = models.IntegerField(blank=True, null=True)
    numer_lekarza = models.IntegerField(blank=True, null=True)
    data_wizyty = models.TextField(primary_key=True)
    koszt = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'wizyta'

class Zalecenia(models.Model):
    numer_pacjenta = models.IntegerField(blank=True, null=True)
    numer_lekarza = models.IntegerField(blank=True, null=True)
    data_wizyty = models.TextField(primary_key=True)
    koszt = models.IntegerField(blank=True, null=True)
    recepta = models.IntegerField(blank=True, null=True)
    szczegol = models.TextField(blank=True, null=True)
    badania = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'zalecenia'


class Cennik(models.Model):
    imie = models.TextField(blank=True, null=True)
    nazwisko = models.TextField(blank=True, null=True)
    specjalizacja = models.TextField(blank=True, null=True)
    obrazek = models.ImageField(upload_to='administracja/pic/',blank=True)
    koszt = models.IntegerField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'cennik'
class Category(models.Model):
    name = models.TextField(blank=True, null=True)
    slug = models.SlugField(max_length=200,db_index=True,unique=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('administracja:product_list_by_category',
                       args=[self.slug])
        
class Product(models.Model):
    category = models.TextField(blank=True, null=True)
    name = models.TextField(blank=True, null=True)
    slug = models.SlugField(max_length=200,db_index=True)
    image = models.ImageField(upload_to="products",blank=True)
    imie = models.TextField(blank=True, null=True)
    nazwisko = models.TextField(blank=True, null=True)
    cena = models.IntegerField(blank=True, null=True)

    class Meta:
        ordering=('name',)
        index_together=(('id','slug'),)
    def __str__(self):
        return self.name
		
    def get_absolute_url(self):
        return reverse('administracja:product_detail',
                       args=[self.id, self.slug])

administracja/forms.py
from django.contrib.auth.models import User
from django import forms

class LoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField(widget=forms.PasswordInput)

class UserRegistrationForm(forms.ModelForm):
    password=forms.CharField(label="Hasło",widget=forms.PasswordInput)
    password2=forms.CharField(label="Powtórz hasło",widget=forms.PasswordInput)


    class Meta:
        model=User
        fields=('username','first_name')

        def clean_password2(self):
            cd=self.cleaned_data
            if cd['password']!=cd['password2']:
                raise forms.ValidationError('Hasła nie są identyczne')
            return cd['password2']

administracja/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from .models import Lekarze,Cennik,Category,Product
from .forms import LoginForm,UserRegistrationForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required

def product_list(request,category_slug=None):
    category=None
    categories=Category.objects.all()
    products=Product.objects.filter()
    if category_slug:
        category=get_object_or_404(Category,slug=category_slug)
        products=products.filter(category=category)
    return render(request,'administracja/product/list.html',{'category':category,'categories':categories,'products':products})
def product_detail(request,id,slug):
    product=get_object_or_404(Product,id=id,slug=slug)
    return render(request,'administracja/product/detail.html',{'product':product})


def dashboard(request):
    products=Product.objects.all()
    context={
        'products': products
        }
    return render(request,
                  'administracja/product/list.html',
                  context)

@login_required
def pass_change(request):
    return render(request,
                  'password_change.html',
                  {'section': 'password_change'})

@login_required
def password_change_done(request):
    return render(request,
                  'administracja/password_change_done.html',
                  {'section': 'administracja/password_change_done'})  
                   
def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Uwierzytelnienie zakończyło się sukcesem.')
                    
                else:
                    return HttpResponse('Konto jest zablokowane.')
            else:
                return HttpResponse('Nieprawidłowe dane uwierzytelniające.')
    else:
        form = LoginForm()
    return render(request, 'administracja/login.html', {'form': form})
   
   

def register(request):
    user_form=UserRegistrationForm(request.POST)
    if request.method=="POST":
        user_form=UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user=user_form.save(commit=False)
            new_user.set_password(
                user_form.cleaned_data['password'])
            new_user.save()
            return render(request,'register_done.html',{'new_user':new_user})
        else:
            user_form=UserRegistrationForm()
    return render(request,'register.html',{'user_form':user_form})

def index(request):
    lek=Lekarze.objects.all()
    context={
        'lek': lek
        }
    return render(request,"index.html",context)

def lista_lekarzy(request):
    lek=Lekarze.objects.all()
    context={
        'lek': lek
        }
    return render(request,"lista_lekarzy.html",context)
def oferta(request):
    products=Product.objects.all()
    context={
        'products': products
        }
    return render(request,"'administracja/product/list.html'",context)
@login_required
def cenniki(request):
    ceny=Cennik.objects.filter()
    context={
        'ceny': ceny
        }
    return render(request,{'ceny':ceny})

def cennik_pojedynczy(request):
    cena=get_object_or_404(Cennik,name=name)
    
    return render(request,'cennik.html',{'cena':cena})

def cennik_not_logged(request):
    ceny=Cennik.objects.all()
    context={
        'ceny': ceny
        }
    return render(request,"cennik_not_logged.html",context)

# Create your views here.

administracja/templates/administracja/dashboard.html
{% extends "base.html" %}

{% block title %}Panel główny{% endblock %}

{% block content %}
  <h1>Panel główny</h1>
  
  <div id="sidebar">
    <h3>Kategorie</h3>
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url "administracja:product_list" %}">Wszystkie</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  
  <div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Nasi specjaliści{% endif %}</h1>
   
    {% for product in products %}
    {<h2>{{ product.imie }} {{ product.nazwisko }} - {{ product.name }} {{ product.cena }} zł</h2> 
      <div class="item">
        <a href="{{ product.get_absolute_url }}">
          <img src="{% if product.image %}{{ product.image.url }}{% endif %}">
        </a>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
        {{ product.cena }} zł
      </div>
    {% endfor %}
  </div>


{% endblock %}

administracja/templates/administracja/login.html
{% extends 'base.html' %}
{% block title %}Logowanie{% endblock %}
{% block content %}
    <h1>Logowanie</h1>
    <p>Wypełnij poniższy formularz,żeby się zalogować:</p>
    <form action="." method="post"> 
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Zaloguj"></p>

    </form>
{% endblock %}

administracja/templates/administracja/password_change_done.html
{% extends "base.html" %}

{% block title %}Hasło zostało zmienione{% endblock %}

{% block content %}
  <h1>Hasło zostało zmienione</h1>
  <p>Zmiana hasła zakończyła się powodzeniem.</p>
{% endblock %}

administracja/templates/administracja/password_change_form.html
{% extends "base.html" %}

{% block title %}Zmiana hasła{% endblock %}

{% block content %}
  <h1>Zmiana hasła</h1>
  <p>Wypełnij poniższy formularz, aby zmienić hasło.</p>
  <form action="." method="post">
    {{ form.as_p }}
    <p><input type="submit" value="Zmień"></p>
    {% csrf_token %}
  </form>
{% endblock %}

administracja/templates/administracja/register.html
{% extends "base.html" %}

{% block title %}Utwórz konto{% endblock %}

{% block content %}
  <h1>Utwórz konto</h1>
  <p>Wypełnij poniższy formularz, aby się zarejestrować:</p>
<form action="." method="post">
    {{ user_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Utwórz konto"></p>
  </form>
{% endblock %}

administracja/templates/administracja/register_done.html
{% extends "base.html" %}

{% block title %}Witaj{% endblock %}

{% block content %}
  <h1>Witaj, {{ new_user.first_name }}!</h1>
  <p>Twoje konto zostało utworzone. Możesz się już <a href="{% url "administracja:login" %}">zalogować</a>.</p>
{% endblock %}